INSERT INTO ds_tingkat
(subskala, level, urutan, nama_id, nama_en, nama_tr, nama_zh, kett, kett_en, kett_tr, kett_zh)
VALUES
('D','H',1,'Depresi - Ringan','Depression - Mild','Depresyon - Hafif','抑郁 - 轻度',
 'Gejala depresi ringan terdeteksi. Cobalah untuk tetap aktif secara sosial, jaga pola tidur, dan bicarakan perasaan Anda dengan orang terdekat.',
 'Mild depressive symptoms detected. Try to stay socially active, maintain a regular sleep schedule, and talk about your feelings with someone close to you.',
 'Hafif düzeyde depresyon belirtisi tespit edildi. Sosyal olarak aktif kalmaya, düzenli uyku alışkanlığı sürdürmeye ve hislerinizi yakınlarınızla paylaşmaya çalışın.',
 '检测到轻度抑郁症状。尝试保持社交活跃、维持规律的睡眠，并与亲近的人谈谈您的感受。'),
('D','O',2,'Depresi - Sedang','Depression - Moderate','Depresyon - Orta','抑郁 - 中度',
 'Gejala depresi tingkat sedang terdeteksi. Disarankan untuk berkonsultasi dengan konselor atau psikolog kampus untuk pendampingan lebih lanjut.',
 'Moderate depressive symptoms detected. It is recommended to consult a counselor or campus psychologist for further guidance.',
 'Orta düzeyde depresyon belirtisi tespit edildi. Daha fazla destek için bir danışman veya kampüs psikoloğuyla görüşmeniz önerilir.',
 '检测到中度抑郁症状。建议咨询辅导员或校园心理师以获得进一步的支持。'),
('D','A',3,'Depresi - Berat','Depression - Severe','Depresyon - Ağır','抑郁 - 重度',
 'Gejala depresi tingkat berat terdeteksi. Segera lakukan konsultasi dengan psikolog atau psikiater untuk penanganan profesional.',
 'Severe depressive symptoms detected. Please consult a psychologist or psychiatrist immediately for professional care.',
 'Ağır düzeyde depresyon belirtisi tespit edildi. Profesyonel destek için lütfen bir psikolog veya psikiyatriste başvurun.',
 '检测到重度抑郁症状。请立即咨询心理师或精神科医生以获得专业治疗。'),
('D','CA',4,'Depresi - Sangat Berat','Depression - Extremely Severe','Depresyon - Çok Ağır','抑郁 - 非常严重',
 'Gejala depresi sangat berat terdeteksi. Segera cari bantuan profesional (psikiater) sesegera mungkin. Jika muncul pikiran untuk menyakiti diri sendiri, segera hubungi layanan darurat atau orang terdekat.',
 'Extremely severe depressive symptoms detected. Seek professional help (psychiatrist) as soon as possible. If you have thoughts of self-harm, contact emergency services or someone close to you immediately.',
 'Çok ağır düzeyde depresyon belirtisi tespit edildi. En kısa sürede profesyonel yardım (psikiyatrist) alın. Kendinize zarar verme düşünceleriniz varsa hemen acil yardım hattını veya yakınlarınızı arayın.',
 '检测到非常严重的抑郁症状。请尽快寻求专业帮助（精神科医生）。如果出现自我伤害的想法，请立即联系紧急服务或身边的人。'),
('A','H',1,'Anxiety - Ringan','Anxiety - Mild','Anksiyete - Hafif','焦虑 - 轻度',
 'Gejala kecemasan ringan terdeteksi. Coba teknik relaksasi pernapasan dan kelola waktu istirahat dengan baik.',
 'Mild anxiety symptoms detected. Try breathing relaxation techniques and manage your rest time well.',
 'Hafif düzeyde kaygı belirtisi tespit edildi. Nefes egzersizleri deneyin ve dinlenme sürenizi iyi yönetin.',
 '检测到轻度焦虑症状。尝试呼吸放松技巧，并合理安排休息时间。'),
('A','O',2,'Anxiety - Sedang','Anxiety - Moderate','Anksiyete - Orta','焦虑 - 中度',
 'Gejala kecemasan tingkat sedang terdeteksi. Disarankan berkonsultasi dengan konselor untuk mempelajari teknik manajemen kecemasan.',
 'Moderate anxiety symptoms detected. It is recommended to consult a counselor to learn anxiety management techniques.',
 'Orta düzeyde kaygı belirtisi tespit edildi. Kaygı yönetim tekniklerini öğrenmek için bir danışmanla görüşmeniz önerilir.',
 '检测到中度焦虑症状。建议咨询辅导员学习焦虑管理技巧。'),
('A','A',3,'Anxiety - Berat','Anxiety - Severe','Anksiyete - Ağır','焦虑 - 重度',
 'Gejala kecemasan tingkat berat terdeteksi. Segera konsultasikan dengan psikolog atau psikiater untuk penanganan lebih lanjut.',
 'Severe anxiety symptoms detected. Please consult a psychologist or psychiatrist immediately for further care.',
 'Ağır düzeyde kaygı belirtisi tespit edildi. Lütfen daha fazla destek için bir psikolog veya psikiyatriste başvurun.',
 '检测到重度焦虑症状。请立即咨询心理师或精神科医生以获得进一步治疗。'),
('A','CA',4,'Anxiety - Sangat Berat','Anxiety - Extremely Severe','Anksiyete - Çok Ağır','焦虑 - 非常严重',
 'Gejala kecemasan sangat berat terdeteksi. Segera cari bantuan profesional (psikiater) karena kecemasan pada tingkat ini dapat sangat mengganggu aktivitas sehari-hari.',
 'Extremely severe anxiety symptoms detected. Seek professional help (psychiatrist) immediately, as anxiety at this level can significantly disrupt daily activities.',
 'Çok ağır düzeyde kaygı belirtisi tespit edildi. Bu düzeydeki kaygı günlük yaşamı ciddi şekilde etkileyebileceğinden en kısa sürede profesyonel yardım (psikiyatrist) alın.',
 '检测到非常严重的焦虑症状。由于此程度的焦虑可能严重影响日常生活，请立即寻求专业帮助（精神科医生）。'),
('S','H',1,'Stres - Ringan','Stress - Mild','Stres - Hafif','压力 - 轻度',
 'Gejala stres ringan terdeteksi. Luangkan waktu untuk beristirahat dan melakukan aktivitas yang Anda sukai.',
 'Mild stress symptoms detected. Take time to rest and engage in activities you enjoy.',
 'Hafif düzeyde stres belirtisi tespit edildi. Dinlenmeye vakit ayırın ve keyif aldığınız aktivitelere zaman ayırın.',
 '检测到轻度压力症状。请抽出时间休息，并从事您喜欢的活动。'),
('S','O',2,'Stres - Sedang','Stress - Moderate','Stres - Orta','压力 - 中度',
 'Gejala stres tingkat sedang terdeteksi. Coba kelola beban tugas dan pertimbangkan konsultasi dengan konselor kampus.',
 'Moderate stress symptoms detected. Try to manage your workload and consider consulting a campus counselor.',
 'Orta düzeyde stres belirtisi tespit edildi. İş yükünüzü yönetmeye çalışın ve bir kampüs danışmanıyla görüşmeyi düşünün.',
 '检测到中度压力症状。请尝试管理您的工作负荷，并考虑咨询校园辅导员。'),
('S','A',3,'Stres - Berat','Stress - Severe','Stres - Ağır','压力 - 重度',
 'Gejala stres tingkat berat terdeteksi. Disarankan segera berkonsultasi dengan psikolog untuk mempelajari strategi manajemen stres yang efektif.',
 'Severe stress symptoms detected. It is recommended to consult a psychologist immediately to learn effective stress management strategies.',
 'Ağır düzeyde stres belirtisi tespit edildi. Etkili stres yönetimi stratejileri öğrenmek için en kısa sürede bir psikologla görüşmeniz önerilir.',
 '检测到重度压力症状。建议立即咨询心理师，学习有效的压力管理策略。'),
('S','CA',4,'Stres - Sangat Berat','Stress - Extremely Severe','Stres - Çok Ağır','压力 - 非常严重',
 'Gejala stres sangat berat terdeteksi. Segera cari bantuan profesional (psikolog/psikiater) karena tingkat stres ini berisiko mempengaruhi kesehatan fisik dan mental secara signifikan.',
 'Extremely severe stress symptoms detected. Seek professional help (psychologist/psychiatrist) immediately, as this level of stress risks significantly affecting your physical and mental health.',
 'Çok ağır düzeyde stres belirtisi tespit edildi. Bu düzeydeki stres fiziksel ve ruhsal sağlığınızı ciddi şekilde etkileme riski taşıdığından en kısa sürede profesyonel yardım (psikolog/psikiyatrist) alın.',
 '检测到非常严重的压力症状。由于此程度的压力可能严重影响您的身心健康，请立即寻求专业帮助（心理师/精神科医生）。');
